feat: require claim to be present to allow access to the user
freifunkMUC/wg-access-server pull request #259
Opened 2022-10-09 12:44 UTC by nextsux

2022-10-24 12:26 UTC, GoliathLabs commented
@nextsux has this been properly tested?

2022-10-24 12:30 UTC, nextsux commented
I have it in production and it works nicely @GoliathLabs

2022-10-24 12:57 UTC, GoliathLabs approved these changes

2022-11-06 17:57 UTC, DasSkelett requested changes

2022-11-06 17:57 UTC, DasSkelett commented on cmd/serve/main.go
> +		if user.Provider == conf.Auth.OIDC.Name && conf.Auth.OIDC.AccessClaim != "" {
```suggestion
		if conf.Auth.OIDC != nil && user.Provider == conf.Auth.OIDC.Name && conf.Auth.OIDC.AccessClaim != "" {
```

`conf.Auth.OIDC` is `nil` if OIDC is disabled -> 
```
runtime error: invalid memory address or nil pointer dereference
  github.com/freifunkMUC/wg-access-server/cmd/serve.claimsMiddleware.func1(0xc0002f6060)
    wg-access-server/cmd/serve/main.go:373
```

2022-11-15 17:20 UTC, DasSkelett approved these changes
Looks good now, thanks for the contribution and sorry for the delay!

2022-11-15 17:20 UTC, merged